### ISSUE TITLE
Add Canonical URL in https://www.ptt.cc/ask/over18

### ISSUE THREAD

**Issue by kidwm** [ptt/pttweb#1]
or Open Graph URL for the from web page.

**Comment by wens** [comment]
Can you elaborate? What do you expect to be the canonical URL?

**Comment by kidwm** [comment]
for example:
the canonical URL of `https://www.ptt.cc/ask/over18?from=%2Fbbs%2FGossiping%2FM.1510632460.A.B25.html` should be `https://www.ptt.cc/ask/over18`

I proposed this is because google search engine index this page with many `from` URLs at that time, if you think this is not a problem any more, I'm fine to close it.
