### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by wade-fs** [ptt/pttweb#14]
Is there any document for install pttweb?

I do the following:

export GOPATH="$HOME/go"
go get -u github.com/ptt/pttweb
......
but failed:

$ go get -u github.com/ptt/pttweb
go: finding github.com/ptt/pttweb latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/net latest
go: finding github.com/rvelhote/go-recaptcha latest
go: finding golang.org/x/sys latest
go: finding google.golang.org/genproto latest
build github.com/ptt/pttweb: cannot load github.com/ptt/pttweb/proto/api: module github.com/ptt/pttweb@latest found (v0.0.0-20200321233133-7aff4bb7b273), but does not contain package github.com/ptt/pttweb/proto/api

I suspect it is a golang version issue. Is it true? If yes, could tell me the supported go version?
If no, could tell me the install environment requirements or the install steps?

**Comment by robertabcd** [comment]
You will need to generate protobuf code, as this part wasn't checked in. Please see the commands in CI script:
https://github.com/ptt/pttweb/blob/master/.travis.yml#L18-L20

**Comment by wade-fs** [comment]
Hello, sir,
  Thank you for your reply soon.
  I think the issue came from the "permission" or "environment". 
  I try "sudo make -C go/pkg/mod/github.com/ptt/pttweb@v0.0.0-20200321233133-7aff4bb7b273/proto" to replace origin "make -C github.com/ptt/pttweb/proto"

  If I tried run as "root", it still failed. It means that I run with normal user, but replace sudo in "make -C ..." in above.

**Comment by holishing** [comment]
you have to install `golang-goprotobuf-dev`
